import type { I18n } from './types';

/** Convictions de méthode. Source : ancien site (blocs vision_*). */
export const visions: { title: I18n; desc: I18n }[] = [
  { title: { fr: 'Maîtrise du cycle de vie', en: 'Full Lifecycle Mastery' }, desc: { fr: 'De la conception (rédaction du cahier des charges) à la mise en production, j\'assure le pilotage complet du projet. Je définis les jalons, sécurise les phases de développement et encadre la recette pour garantir un livrable conforme aux attentes.', en: 'From conception (requirements specification) to production deployment, I ensure complete project steering. I define milestones, secure development phases, and oversee acceptance testing to guarantee a deliverable that meets expectations.' } },
  { title: { fr: 'Le trait d\'union Métier / IT', en: 'The Business / IT Bridge' }, desc: { fr: 'Un Chef de Projet doit être capable de parler aux développeurs comme aux équipes métiers. Mon rôle est de traduire les besoins opérationnels en solutions concrètes (spécifications) et d\'assurer une coordination fluide entre les experts internes et externes.', en: 'A Project Manager must be able to speak to developers and business teams alike. My role is to translate operational needs into concrete solutions (specifications) and ensure smooth coordination between internal and external experts.' } },
  { title: { fr: 'Agilité & Intrapreneuriat', en: 'Agility & Intrapreneurship' }, desc: { fr: 'Habitué à l\'esprit start-up, j\'encourage l\'expérimentation, les méthodes agiles (test & learn, itérations) et la curiosité. J\'aime sortir des sentiers battus pour proposer des améliorations continues et innover dans les approches.', en: 'Accustomed to the startup mindset, I encourage experimentation, agile methods (test & learn, iterations) and curiosity. I enjoy thinking outside the box to propose continuous improvements and innovative approaches.' } },
  { title: { fr: 'Pilotage par la valeur (ROI)', en: 'Value-Driven Steering (ROI)' }, desc: { fr: 'Chaque projet doit avoir un impact mesurable. Je m\'appuie sur le suivi de la qualité, des coûts et des délais (QCD) ainsi que sur la data pour animer les comités de pilotage (COPIL), arbitrer les priorités et garantir la création de valeur.', en: 'Every project must have a measurable impact. I rely on quality, cost, and schedule tracking (QCS) along with data to lead steering committees (COPIL), arbitrate priorities, and ensure value creation.' } },
];
